### ISSUE TITLE
Sentry Version 8.0

### ISSUE THREAD

**Issue by onlydole** [slafs/sentry-docker#48]
Hello @slafs! 

I wanted to know when you might have version 8.0 of Sentry available and tagged, and if there is anything that needs to be done to get this ready, I'd be more than happy to help!

**Comment by andrew-dixon** [comment]
@onlydole - See https://github.com/slafs/sentry-docker/issues/40

**Comment by onlydole** [comment]
:+1:

**Comment by onlydole** [comment]
When will this be tackled?

**Comment by milanvanschaik** [comment]
"A new configuration file, config.yml has been introduced. This new file is generated during sentry init
the first time, and expected to be pointed at a directory. config.yml is the home for new configuration options that will be moved from the existing python config file.

SENTRY_URL_PREFIX has been deprecated, and moved to system.url-prefix inside of config.yml or it
can be configured at runtime."

So that needs to be fixed. Also I noticed SENTRY_ADMIN_EMAIL is deprecated:
"DeprecationWarning: SENTRY_ADMIN_EMAIL is deprecated.Use SENTRY_OPTIONS instead, key 'system.admin-email'
  "Use SENTRY_OPTIONS instead, key 'system.admin-email'", DeprecationWarning)"

**Comment by mlegenhausen** [comment]
+1

**Comment by lorenz** [comment]
+1

**Comment by onlydole** [comment]
:+1:

**Comment by slafs** [comment]
Thanks for comments. Everyone interested in this please see #51. Please build and try out from `next/sentry-8.0` branch and give feedback.

**Comment by onlydole** [comment]
@slafs - This works for me!
